classDiagram

    class AddressBook{
        - contacts : List<com.app.Contact>
        + addContact(contact: com.app.Contact) void
        + removeContact(criteria: String): List<com.app.Contact>
        + searchContact(criteria: String) List<com.app.Contact>
        + displayAllContacts(): List<com.app.Contact>
        + editContact(oldContact: com.app.Contact, newContact: com.app.Contact): void
    }

    class Contact{
        - name: String
        - phoneNumber: String
        - email: String
        + getName():String
        + getPhoneNumber() String
        + getEmail(): String
        + setName(name: String): void
        + setPhoneNumber(PhoneNumber: String) void
        + setEmail(email: String) void
    }

    class ContactManager {
        + addContact(contact: com.app.Contact) void
        + removeContact(criteria: String): List<com.app.Contact>
        + updateContact(oldContact: com.app.Contact, newContact: com.app.Contact): void
        + removeAllContacts(deleteAllContacts: String): List<com.app.Contact>

    }

    class SearchEngine {
        + searchName(name: String): List<com.app.Contact>
        + searchPhone(PhoneNumber: String): List<com.app.Contact>
        + searchEmail(email: String): LIst<com.app.Contact>

    }

    class UserInterface {
    + displayMenu(): void
    + userInput(): String
    + displayResults(results: List<com.app.Contact>): void
    + displayContacts(contact: com.app.Contact): void
    }

    class FileHandler {

    }

    class Display {
        + contactsDisplayAlphabet(contact: com.app.Contact): void
    }
    class DangerAllContacts {
        + deleteAllContacts():
        + confirmDeleteAllContacts(confirm: String):
    }

AddressBook  --> ContactManager
ContactManager --> SearchEngine